name: Generate PDF Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'resources/**'
      - 'docsify-to-pdf.sh'

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Make script executable
        run: chmod +x ./docsify-to-pdf.sh
      
      - name: Generate PDF documentation
        run: ./docsify-to-pdf.sh

      - name: Upload PDF documentation
        uses: actions/upload-artifact@v3
        with:
          name: auxiliary-documentation
          path: pdf/docs.pdf
          retention-days: 90
