name: Generate PDF Documentation

on:
  push:
    branches: [ main, master ]

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Make script executable
        run: chmod +x ./docsify-to-pdf.sh
      
      - name: Generate PDF documentation
        run: |
          # Modified version of your script for CI environment
          docker pull ghcr.io/kernoeb/docker-docsify-pdf:latest
          mkdir -p ./pdf
          
          docker run --rm \
            --cap-add=SYS_ADMIN \
            -v ${{ github.workspace }}/docs:/home/node/docs:ro \
            -v ${{ github.workspace }}/pdf:/home/node/pdf:rw \
            -v ${{ github.workspace }}/resources/covers/cover.pdf:/home/node/resources/cover.pdf:ro \
            -e "PDF_OUTPUT_NAME=docs.pdf" \
            ghcr.io/kernoeb/docker-docsify-pdf:latest

      - name: Upload PDF documentation
        uses: actions/upload-artifact@v3
        with:
          name: auxiliary-documentation
          path: pdf/docs.pdf
          retention-days: 90
